### PR TITLE
added support for m1 mac

### PR DESCRIPTION
**Pull request by iamwille-dev**
I was able to get it to run on my m1 mac with a couple tweaks. Still needs to be optimized but it works

### CODE REVIEW

**Comment by AndrewBreyen** [comment]
@enemaliwilliam Is this ONLY for Apple Silicon macs? would love to get it working on Intel too! 

Currently getting this on my Intel mac when running `pip install -r requirements.txt`:
```
Building wheels for collected packages: openai-whisper, pyaudio
  Building wheel for openai-whisper (pyproject.toml) ... done
  Created wheel for openai-whisper: filename=openai_whisper-20230314-py3-none-any.whl size=796901 sha256=e71ad9dbd48dbac475263b4e66ae50ebe22bfff9c46b948efa8b70a7809dcc1d
  Stored in directory: /Users/abreyen/Library/Caches/pip/wheels/b2/13/5f/fe8245f6dc59df505879da4b2129932e342f02a80e6b87f27d
  Building wheel for pyaudio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12.6-x86_64-cpython-310
      creating build/lib.macosx-12.6-x86_64-cpython-310/pyaudio
      copying src/pyaudio/__init__.py -> build/lib.macosx-12.6-x86_64-cpython-310/pyaudio
      running build_ext
      building 'pyaudio._portaudio' extension
      creating build/temp.macosx-12.6-x86_64-cpython-310
      creating build/temp.macosx-12.6-x86_64-cpython-310/src
      creating build/temp.macosx-12.6-x86_64-cpython-310/src/pyaudio
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -DMACOS=1 -I/usr/local/include -I/usr/include -I/opt/homebrew/include -I/Users/abreyen/.pyenv/versions/3.10.8/include/python3.10 -c src/pyaudio/device_api.c -o build/temp.macosx-12.6-x86_64-cpython-310/src/pyaudio/device_api.o
      src/pyaudio/device_api.c:9:10: fatal error: 'portaudio.h' file not found
      #include "portaudio.h"
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyaudio
Successfully built openai-whisper
Failed to build pyaudio
ERROR: Could not build wheels for pyaudio, which is required to install pyproject.toml-based projects
```

**Comment by zarifpour** [comment]
@enemaliwilliam I am getting this error when I try to run on an M1 Max:

```
❯ python main.py
.../ecoute/ecoute_env/lib/python3.11/site-packages/whisper/timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
Traceback (most recent call last):
  File ".../ecoute/AudioRecorder.py", line 25, in adjust_for_noise
    self.recorder.adjust_for_ambient_noise(self.source)
  File ".../ecoute/custom_speech_recognition/__init__.py", line 402, in adjust_for_ambient_noise
    assert source.stream is not None, "Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../ecoute/main.py", line 121, in <module>
    main()
  File ".../ecoute/main.py", line 78, in main
    speaker_audio_recorder = AudioRecorder.DefaultSpeakerRecorder()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../ecoute/AudioRecorder.py", line 63, in __init__
    self.adjust_for_noise("Default Speaker", "Please make or play some noise from the Default Speaker...")
  File ".../ecoute/AudioRecorder.py", line 24, in adjust_for_noise
    with self.source:
  File ".../ecoute/custom_speech_recognition/__init__.py", line 208, in __exit__
    self.stream.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

```

File: AudioRecorder.py [hunk 1]
```diff
@@ -34,17 +39,20 @@ def __init__(self):
...
+                if not default_speakers["isLoopbackDevice"]:
+                    for loopback in p.get_loopback_device_info_generator():
+                        if default_speakers["name"] in loopback["name"]:
+                            default_speakers = loopback
+                            break
+                    else:
+                        print("[ERROR] No loopback device found.")
+        else:
+            p = pyaudio.PyAudio()
+            default_speakers = p.get_device_info_by_index(0)
```
Comment (zarifpour) [inline AudioRecorder.py:55]: This line is the culprit. I had my LG HDR 4K external monitor plugged into my macbook and this causes the issue I described in our conversation. Since we get `p.get_device_info_by_index(0)` and my LG HDR 4K is detected as the first index, this causes the error.

CleanShot_2023-05-30_21 59 09_System Settings_000850@2x

If I unplug the device or [keep it plugged in and] switch the index to 1 to match the appropriate index of my default speakers, the issue is resolved.

Comment (zarifpour) [reply AudioRecorder.py:55]: Perhaps we can update the documentation or add a GUI to select appropriate default speakers?

**Comment by brimbela** [comment]
Got it running on my M1 Macbook, but nothing "happened".
I'm using a headset.
Any advise on the hardware setup?

**Review by flexbox — APPROVED** [review]
💯

**Comment by brimbela** [comment]
> 

I'm now trying with default speakers.
It should be ok:
`>>> p.get_device_info_by_index(1)
{'index': 1, 'structVersion': 2, 'name': 'MacBook Pro Microphone', 'hostApi': 0, 'maxInputChannels': 1, 'maxOutputChannels': 0, 'defaultLowInputLatency': 0.0336875, 'defaultLowOutputLatency': 0.01, 'defaultHighInputLatency': 0.043020833333333335, 'defaultHighOutputLatency': 0.1, 'defaultSampleRate': 48000.0}`
But nothing happens.
Will add some logging to understand a bit better whats going on.

**Review by zarifpour — APPROVED** [review]

**Review by oldsongsz — CHANGES_REQUESTED** [review]
I don't agree such hard coded way. the device index is variable to different compuaters and conditions. There should be more elegant solutions.

File: AudioRecorder.py [hunk 2]
```diff
@@ -1,6 +1,11 @@
 import custom_speech_recognition as sr
-import pyaudiowpatch as pyaudio
 from datetime import datetime
+import os
+
+if os.name == 'nt':
```
Comment (SevaSk) [inline AudioRecorder.py:5]: 1) Try to refactor to set up all differences between windows and MAC in one place. Dependency injection looks appropriate here open for other approach's to keep code clean.

File: AudioRecorder.py [hunk 3]
```diff
@@ -34,17 +39,20 @@ def __init__(self):
...
-            default_speakers = p.get_device_info_by_index(wasapi_info["defaultOutputDevice"])
-            
-            if not default_speakers["isLoopbackDevice"]:
-                for loopback in p.get_loopback_device_info_generator():
-                    if default_speakers["name"] in loopback["name"]:
-                        default_speakers = loopback
-                        break
-                else:
-                    print("[ERROR] No loopback device found.")
+        if os.name == 'nt':
```
Comment (SevaSk) [inline AudioRecorder.py:42]: DefaultSpeakerRecorder should be agnostic to operating system. Same as point 1)

File: AudioTranscriber.py [hunk 4]
```diff
@@ -7,9 +7,14 @@
 import custom_speech_recognition as sr
 import io
 from datetime import timedelta
-import pyaudiowpatch as pyaudio
 from heapq import merge
 
+if os.name == 'nt':
```
Comment (SevaSk) [inline AudioTranscriber.py:12]: same as 1)

File: README.md [hunk 5]
```diff
@@ -20,6 +20,11 @@ Follow these steps to set up and run Ecoute on your local machine.
 - Windows OS (Not tested on others)
 - FFmpeg 
 
+
+
+
+<details>
+<summary>Windows</summary>
```
Comment (SevaSk) [inline README.md:27]: Nice!

File: custom_speech_recognition/__init__.py [hunk 6]
```diff
@@ -107,7 +107,10 @@ def get_pyaudio():
         Imports the pyaudio module and checks its version. Throws exceptions if pyaudio can't be found or a wrong version is installed
         """
         try:
-            import pyaudiowpatch as pyaudio
+            if os.name == 'nt':
```
Comment (SevaSk) [inline custom_speech_recognition/__init__.py:110]: 1)

File: requirements.txt [hunk 7]
```diff
@@ -3,6 +3,9 @@ openai-whisper==20230314
 Wave==0.0.2
 openai==0.27.6
 customtkinter==5.1.3
-PyAudioWPatch==0.2.12.5
 --extra-index-url https://download.pytorch.org/whl/cu117
-torch
\ No newline at end of file
+torch
```
Comment (SevaSk) [inline requirements.txt:7]: Nice!

**Review by SevaSk — CHANGES_REQUESTED** [review]
Thank you for your contribution! I've left some comments on your work. Unfortunately, I don't have any specific contributing guidelines to facilitate easier approval for your pull requests. However, I recommend following industry best practices and considering the feedback provided. Please feel free to express disagreements with the design decisions I've made. Although I may not always have time to assist directly, I will be sure to approve your changes when they align with my perspective or when you manage to change my mind.

**Comment by vikkastaneja** [comment]
pip install -r requirements.txt gives me the following error on macos with m1 chip.

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Collecting numpy==1.24.3 (from -r requirements.txt (line 1))
  Using cached numpy-1.24.3-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
Collecting openai-whisper==20230314 (from -r requirements.txt (line 2))
  Using cached openai-whisper-20230314.tar.gz (792 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Wave==0.0.2 (from -r requirements.txt (line 3))
  Using cached Wave-0.0.2.zip (38 kB)
  Preparing metadata (setup.py) ... done
Collecting openai==0.27.6 (from -r requirements.txt (line 4))
  Using cached openai-0.27.6-py3-none-any.whl (71 kB)
Collecting customtkinter==5.1.3 (from -r requirements.txt (line 5))
  Using cached customtkinter-5.1.3-py3-none-any.whl (295 kB)
ERROR: Could not find a version that satisfies the requirement PyAudioWPatch==0.2.12.5 (from versions: none)
ERROR: No matching distribution found for PyAudioWPatch==0.2.12.5

**Comment by mrdavidlaing** [comment]
I couldn't get this to work on Mac M1 with Python v`3.10.10`.

This kept throwing the error:
```
RuntimeError: tk.h version (8.5) doesn't match libtk.a version (8.6)
```

I could however get it to work with an older Python version - v`3.9.8`

**Comment by ryanxjhan** [comment]
I got it running, and my UI is working fine on my M2 Pro. No errors whatsoever. But the app couldn't separate the speaker's words and mine. Everything is coming from [You]. I tried to change the `get_device_info_by_index` but it didn't work

**Comment by CyberNinja568** [comment]
Thanks for sharing your project on GitHub! It's impressive to see

**Comment by xiaotianxt** [comment]
> I don't agree such hard coded way. the device index is variable to different compuaters and conditions. There should be more elegant solutions.

I totally agree with you. In fact, on my device (M2 MacBook Air), the code only works when the device index is set to 0, not 1. We definitely need to consider this variability in different setups.

**Comment by alabrashJr** [comment]
I attempted to run it on my M1 Mac, but unfortunately, I encountered an error that I was unable to resolve despite my efforts. I followed the instructions provided in [link](https://www.deskriders.dev/posts/1671901033-installing-pyaudio-mac/), but the issue persisted. Do you have any recommendations for how I can resolve this error?

```
/Users/..../lib/python3.8/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Could not import the PyAudio C module 'pyaudio._portaudio'.
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "/Users/.../ecoute/AudioTranscriber.py", line 15, in <module>
    import pyaudio
  File "/Users/...lib/python3.8/site-packages/pyaudio/__init__.py", line 111, in <module>
    import pyaudio._portaudio as pa
ImportError: dlopen(/Users/.../lib/python3.8/site-packages/pyaudio/_portaudio.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_PaMacCore_SetupChannelMap'
```

**Comment by alabrashJr** [comment]
> I attempted to run it on my Apple M1 Pro, but unfortunately, I encountered an error that I was unable to resolve despite my efforts. I followed the instructions provided in [link](https://www.deskriders.dev/posts/1671901033-installing-pyaudio-mac/), but the issue persisted. Do you have any recommendations for how I can resolve this error?
> 
> ```
> /Users/..../lib/python3.8/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
>   def backtrace(trace: np.ndarray):
> Could not import the PyAudio C module 'pyaudio._portaudio'.
> Traceback (most recent call last):
>   File "main.py", line 2, in <module>
>     from AudioTranscriber import AudioTranscriber
>   File "/Users/.../ecoute/AudioTranscriber.py", line 15, in <module>
>     import pyaudio
>   File "/Users/...lib/python3.8/site-packages/pyaudio/__init__.py", line 111, in <module>
>     import pyaudio._portaudio as pa
> ImportError: dlopen(/Users/.../lib/python3.8/site-packages/pyaudio/_portaudio.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_PaMacCore_SetupChannelMap'
> ```
> 
> versions: Python 3.9.12 pip 23.1.2 pyaudio==0.2.13 Homebrew 4.0.21 Homebrew/homebrew-core (git revision 72cb0f2fe6d; last commit 2023-06-08) Homebrew/homebrew-cask (git revision 9537303472; last commit 2023-06-08)
> 
> ```shell
>  brew info portaudio
> ==> portaudio: stable 19.7.0 (bottled), HEAD
> Cross-platform library for audio I/O
> http://www.portaudio.com
> /opt/homebrew/Cellar/portaudio/HEAD-cb8d3dc (33 files, 546.7KB) *
>   Built from source on 2023-06-08 at 18:31:58
> From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/portaudio.rb
> License: MIT
> ==> Dependencies
> Build: pkg-config ✔
> ==> Options
> --HEAD
> 	Install HEAD version
> ==> Analytics
> install: 7,874 (30 days), 1,289 (90 days), 73,904 (365 days)
> install-on-request: 3,964 (30 days), 967 (90 days), 43,194 (365 days)
> build-error: 0 (30 days)
> ```

I fixed the issue using the Python (v 3.11.3) I installed using brew

**Comment by notjulian** [comment]
this is amazing, work perfectly 
M1 pro

followed this [link](https://www.deskriders.dev/posts/1671901033-installing-pyaudio-mac/) to install `pyaudio `

and also: 

```
brew install python-tk@3.11

python3 --version
Python 3.11.4
```

**Comment by DavidAG2000** [comment]
Why is this not merged yet?

**Comment by ES-Anon** [comment]
> Why is this not merged yet?

Likely because @SevaSk [requested changes](https://github.com/SevaSk/ecoute/pull/40#pullrequestreview-1454160005) that haven't been addressed?

Thank you all for your work on this. Currently testing with my Intel MBP.

**Comment by xjqsusu** [comment]
> 

I'm seeing the same issue, how did you fix it?

**Comment by xjqsusu** [comment]
> @enemaliwilliam I am getting this error when I try to run on an M1 Max:
> 
> ```
> ❯ python main.py
> .../ecoute/ecoute_env/lib/python3.11/site-packages/whisper/timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
>   @numba.jit
> [INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
> [INFO] Completed ambient noise adjustment for Default Mic.
> [INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
> Traceback (most recent call last):
>   File ".../ecoute/AudioRecorder.py", line 25, in adjust_for_noise
>     self.recorder.adjust_for_ambient_noise(self.source)
>   File ".../ecoute/custom_speech_recognition/__init__.py", line 402, in adjust_for_ambient_noise
>     assert source.stream is not None, "Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
> AssertionError: Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".../ecoute/main.py", line 121, in <module>
>     main()
>   File ".../ecoute/main.py", line 78, in main
>     speaker_audio_recorder = AudioRecorder.DefaultSpeakerRecorder()
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File ".../ecoute/AudioRecorder.py", line 63, in __init__
>     self.adjust_for_noise("Default Speaker", "Please make or play some noise from the Default Speaker...")
>   File ".../ecoute/AudioRecorder.py", line 24, in adjust_for_noise
>     with self.source:
>   File ".../ecoute/custom_speech_recognition/__init__.py", line 208, in __exit__
>     self.stream.close()
>     ^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'close'
> ```

I'm seeing the same issue, how did you fix it?

**Comment by xjqsusu** [comment]
> I got it running, and my UI is working fine on my M2 Pro. No errors whatsoever. But the app couldn't separate the speaker's words and mine. Everything is coming from [You]. I tried to change the `get_device_info_by_index` but it didn't work

did you get this fixed? I'm seeing the same issue, which SPEAKER AND YOU are the same, reading the microphone input.

**Comment by FOkvj** [comment]
$ brew install portaudio
then
$ pip install pyaudio
done

**Comment by FOkvj** [comment]
on Intel5 mac
$ brew install portaudio
then
$ pip install pyaudio
done

**Comment by qartheeq** [comment]
*/ecoute/AudioTranscriber.py", line 1, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'

I am receiving this error

**Comment by squadgazzz** [comment]
I've managed to run it on Intel mac
```
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
[INFO] Whisper using GPU: False
READY
```
But I don't see any UI. Does anyone know how to fix it?

**Comment by squadgazzz** [comment]
Hey everyone, I've managed to run it on an Intel Mac. The UI doesn't work on Python earlier 3.11 for a reason: https://github.com/TomSchimansky/CustomTkinter/issues/1690
But it still works weird:
image
No matter what the speaker really said, I see a duplicated speech from myself as a speaker. Any reason for that?

**Comment by squadgazzz** [comment]
This approach doesn't seem to work even close.

1. UI doesn't work on Python earlier 3.11: https://github.com/TomSchimansky/CustomTkinter/issues/1690
2. `pyaudio` doesn't accept speakers as input device here:
```
if self.speaker:
    p = self.audio
    self.stream = Microphone.MicrophoneStream(
        p.open(
            input_device_index=self.device_index,
            channels=self.channels,
            format=self.format,
            rate=self.SAMPLE_RATE,
            frames_per_buffer=self.CHUNK,
            input=True
        )
    )
```
It fails with the `[Errno -9998] Invalid number of channels` because there are `0` input channels available for the output device, which is obvious. And PyAudio doesn't allow to get the input stream from the output device. It requires third-party applications.

**Comment by vskrch** [comment]
> */ecoute/AudioTranscriber.py", line 1, in import whisper ModuleNotFoundError: No module named 'whisper'
> 
> I am receiving this error

+1

**Comment by Esorat** [comment]
Hi. gotta error when UI start after 3 or 5 seconds got this. I give access to mic but still dont undestand. Maybe some know?

ecoute git:(main) ✗ python3 main.py
/Users/mac/anaconda3/lib/python3.11/site-packages/whisper/timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
||PaMacCore (AUHAL)|| Error on line 2712: err=''nope'', msg=Audio Hardware: Illegal Operation
Traceback (most recent call last):
  File "/Users/mac/Desktop/ecoute/AudioRecorder.py", line 28, in adjust_for_noise
    self.recorder.adjust_for_ambient_noise(self.source)
  File "/Users/mac/Desktop/ecoute/custom_speech_recognition/__init__.py", line 402, in adjust_for_ambient_noise
    assert source.stream is not None, "Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/ecoute/main.py", line 128, in <module>
    main()
  File "/Users/mac/Desktop/ecoute/main.py", line 85, in main
    speaker_audio_recorder = AudioRecorder.DefaultSpeakerRecorder()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/ecoute/AudioRecorder.py", line 67, in __init__
    self.adjust_for_noise("Default Speaker", "Please make or play some noise from the Default Speaker...")
  File "/Users/mac/Desktop/ecoute/AudioRecorder.py", line 27, in adjust_for_noise
    with self.source:
  File "/Users/mac/Desktop/ecoute/custom_speech_recognition/__init__.py", line 208, in __exit__
    self.stream.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by hoainho** [comment]
> @enemaliwilliam Is this ONLY for Apple Silicon macs? would love to get it working on Intel too!
> 
> Currently getting this on my Intel mac when running `pip install -r requirements.txt`:
> 
> ```
> Building wheels for collected packages: openai-whisper, pyaudio
>   Building wheel for openai-whisper (pyproject.toml) ... done
>   Created wheel for openai-whisper: filename=openai_whisper-20230314-py3-none-any.whl size=796901 sha256=e71ad9dbd48dbac475263b4e66ae50ebe22bfff9c46b948efa8b70a7809dcc1d
>   Stored in directory: /Users/abreyen/Library/Caches/pip/wheels/b2/13/5f/fe8245f6dc59df505879da4b2129932e342f02a80e6b87f27d
>   Building wheel for pyaudio (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Building wheel for pyaudio (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [18 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.macosx-12.6-x86_64-cpython-310
>       creating build/lib.macosx-12.6-x86_64-cpython-310/pyaudio
>       copying src/pyaudio/__init__.py -> build/lib.macosx-12.6-x86_64-cpython-310/pyaudio
>       running build_ext
>       building 'pyaudio._portaudio' extension
>       creating build/temp.macosx-12.6-x86_64-cpython-310
>       creating build/temp.macosx-12.6-x86_64-cpython-310/src
>       creating build/temp.macosx-12.6-x86_64-cpython-310/src/pyaudio
>       clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -DMACOS=1 -I/usr/local/include -I/usr/include -I/opt/homebrew/include -I/Users/abreyen/.pyenv/versions/3.10.8/include/python3.10 -c src/pyaudio/device_api.c -o build/temp.macosx-12.6-x86_64-cpython-310/src/pyaudio/device_api.o
>       src/pyaudio/device_api.c:9:10: fatal error: 'portaudio.h' file not found
>       #include "portaudio.h"
>                ^~~~~~~~~~~~~
>       1 error generated.
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for pyaudio
> Successfully built openai-whisper
> Failed to build pyaudio
> ERROR: Could not build wheels for pyaudio, which is required to install pyproject.toml-based projects
> ```
@enemaliwilliam 
Let run `brew install portaudio`, Afterward reinstall, it's working as well.

**Comment by shufanhao** [comment]
can be merged ? eager to have this feature.
